# Generated by Django 5.1.2 on 2025-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_atelier_video_url_blogpost_video_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
