# Generated by Django 5.1.2 on 2025-08-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_establishment_logo_alter_sponsor_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atelier",
            name="content",
            field=models.TextField(blank=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="cover_image",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Image de couverture (Cloudinary)",
            ),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="location",
            field=models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=220, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Résumé"),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="video_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Vidéo (Cloudinary)"
            ),
        ),
        migrations.AlterField(
            model_name="atelierimage",
            name="atelier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="main.atelier",
                verbose_name="Atelier",
            ),
        ),
        migrations.AlterField(
            model_name="atelierimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="Légende"),
        ),
        migrations.AlterField(
            model_name="atelierimage",
            name="image_url",
            field=models.URLField(max_length=500, verbose_name="Image (Cloudinary)"),
        ),
        migrations.AlterField(
            model_name="atelierimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="Légende"),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="image_url",
            field=models.URLField(max_length=500, verbose_name="Image (Cloudinary)"),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="main.blogpost",
                verbose_name="Article de blog",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Image de couverture (Cloudinary)",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(blank=True, verbose_name="Extrait"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de publication"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=220, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="video_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Vidéo (Cloudinary)"
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="country",
            field=models.CharField(blank=True, max_length=120, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="logo",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Logo (Cloudinary)"
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="type",
            field=models.CharField(
                choices=[
                    ("school", "École"),
                    ("university", "Université"),
                    ("organization", "Organisation"),
                    ("company", "Entreprise"),
                ],
                default="school",
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="website_url",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Logo (Cloudinary)"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="tier",
            field=models.CharField(
                choices=[
                    ("gold", "Or"),
                    ("silver", "Argent"),
                    ("bronze", "Bronze"),
                    ("partner", "Partenaire"),
                ],
                default="partner",
                max_length=20,
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="website_url",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Photo (Cloudinary)"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(blank=True, max_length=150, verbose_name="Rôle"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="photo",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Photo (Cloudinary)"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="role",
            field=models.CharField(blank=True, max_length=150, verbose_name="Rôle"),
        ),
    ]
