# Generated by Django 5.1.2 on 2025-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_atelier_content_alter_atelier_cover_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Nom & Prénom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("question", "Question générale"),
                            ("partenariat", "Partenariat"),
                            ("inscription", "Inscription"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Sujet",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstablishmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "establishment_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l’établissement"
                    ),
                ),
                (
                    "responsible_name",
                    models.CharField(
                        max_length=150, verbose_name="Nom & Prénom du responsable"
                    ),
                ),
                ("role", models.CharField(max_length=150, verbose_name="Fonction")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Téléphone")),
                (
                    "partnership_types",
                    models.CharField(
                        help_text="Ateliers,Conférences,Expositions,Formation,Autre",
                        max_length=200,
                        verbose_name="Type de partenariat souhaité (CSV)",
                    ),
                ),
                (
                    "participants",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Nombre estimé de participants",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, verbose_name="Message / Détails de la demande"
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d’établissement",
                "verbose_name_plural": "Demandes d’établissements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SponsorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_name",
                    models.CharField(
                        max_length=200, verbose_name="Organisation / Entreprise"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        max_length=150, verbose_name="Nom & Prénom du soumettant"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Fonction"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Téléphone")),
                (
                    "support_types",
                    models.CharField(
                        help_text="Institutionnel,Financier,Matériel,Logistique,Bourses,Autre",
                        max_length=200,
                        verbose_name="Type de soutien (CSV)",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Message complémentaire"),
                ),
            ],
            options={
                "verbose_name": "Demande sponsor",
                "verbose_name_plural": "Demandes sponsors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Nom & Prénom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Téléphone")),
                (
                    "city",
                    models.CharField(
                        max_length=120, verbose_name="Ville / Localisation"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("animation3d", "Animation 3D"),
                            ("logistique", "Logistique"),
                            ("communication", "Communication"),
                            ("administration", "Administration"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Domaine de compétences",
                    ),
                ),
                (
                    "domain_other",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Autre (à préciser)"
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Semaine,Week-end,Vacances scolaires",
                        max_length=200,
                        verbose_name="Disponibilités (CSV)",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True,
                        verbose_name="Pourquoi souhaitez-vous devenir bénévole ?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature bénévole",
                "verbose_name_plural": "Candidatures bénévoles",
                "ordering": ["-created_at"],
            },
        ),
    ]
