# Generated by Django 5.1.2 on 2025-08-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_contactmessage_establishmentrequest_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Establishment",
        ),
        migrations.DeleteModel(
            name="Sponsor",
        ),
        migrations.DeleteModel(
            name="Volunteer",
        ),
    ]
