# Generated by Django 5.1.2 on 2025-09-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_delete_establishment_delete_sponsor_delete_volunteer"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "desc",
                    models.TextField(blank=True, verbose_name="Description courte"),
                ),
                (
                    "long_desc",
                    models.TextField(blank=True, verbose_name="Description longue"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bourses", "Bourses"),
                            ("concours", "Concours"),
                            ("challenges", "Challenges"),
                            ("procedure", "Procédure"),
                            ("dossier", "Mon dossier"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "meta",
                    models.CharField(blank=True, max_length=200, verbose_name="Meta"),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Image de couverture (Cloudinary)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Info",
                "verbose_name_plural": "Infos",
                "ordering": ["-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="InfoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_url",
                    models.URLField(max_length=500, verbose_name="Image (Cloudinary)"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.infoitem",
                        verbose_name="Info",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image info",
                "verbose_name_plural": "Images info",
                "ordering": ["order", "id"],
            },
        ),
    ]
