# Generated by Django 5.1.2 on 2025-09-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_infoitem_infoimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Image (Cloudinary)",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte du bouton"
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Lien du bouton"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début d'affichage"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-created_at"],
            },
        ),
    ]
