# Generated by Django 5.1.2 on 2025-09-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="infoitem",
            name="is_promo",
            field=models.BooleanField(
                default=False, verbose_name="Mettre en avant (popup)"
            ),
        ),
        migrations.AddField(
            model_name="infoitem",
            name="promo_cta_text",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Texte du bouton"
            ),
        ),
        migrations.AddField(
            model_name="infoitem",
            name="promo_cta_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Lien du bouton"
            ),
        ),
        migrations.AddField(
            model_name="infoitem",
            name="promo_end_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin promo"),
        ),
        migrations.AddField(
            model_name="infoitem",
            name="promo_start_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Début promo"
            ),
        ),
    ]
