# Generated by Django 5.1.2 on 2025-09-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_infoitem_is_promo_infoitem_promo_cta_text_and_more"),
        ("main", "0009_remove_announcement"),
    ]

    operations = []
